### ISSUE TITLE
Make Factory/Connection bean loading conditional based on presence of `nats` config property.

### ISSUE THREAD

**Issue by pipefail** [micronaut-projects/micronaut-nats#80]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Install this package
2. Run the application _without_ any NATs configuration in `application.yml`

### Expected Behaviour

Factory conditionally _does not_ load and _does not_ attempt to create NATs connections because configuration is _not present_ in any loaded property sources.

### Actual Behaviour

Factory _does_ load and assumes default `localhost:4222`, attempts to create NATs connections but crashes due to missing configuration values.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 
- **JDK Version:** 8

### Stack trace
```
io.micronaut.context.exceptions.BeanInstantiationException: Error creating connection to nats
	at io.micronaut.nats.connect.NatsConnectionFactory.connection(NatsConnectionFactory.java:55)
	at io.micronaut.nats.connect.$NatsConnectionFactory$Connection0Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:125)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2428)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2414)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2105)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2079)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1093)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at io.micronaut.nats.health.$NatsHealthIndicatorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2748)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2660)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:922)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$9(AbstractBeanDefinition.java:1124)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1762)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1119)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:984)
	at io.micronaut.management.health.monitor.$HealthMonitorTaskDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1714)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2428)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2414)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2105)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2079)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:616)
	at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$5(ScheduledMethodProcessor.java:123)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to connect to NATS servers: nats://localhost:4222.
	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:239)
	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29)
	at io.nats.client.Nats.createConnection(Nats.java:249)
	at io.nats.client.Nats.connect(Nats.java:164)
	at io.micronaut.nats.connect.NatsConnectionFactory.connection(NatsConnectionFactory.java:53)
	... 35 common frames omitted
```

**Comment by grimmjo** [comment]
@graemerocher This only happens if there is a Listener in the bean context and that's why the default configuration is loaded. The Rabbitmq integration shows the same behavior. 

I haven't found a solution. I need some help to solve this issue. `@Requires("nats")` on the `SingleNatsConnectionFactoryConfig` didn't solve the problem.

**Comment by grimmjo** [comment]
This issue should be fixed with the merge request
